<?php
/**
 * @file
 * imagex_widgets_rss.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function imagex_widgets_rss_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'bean-imagex_widget_rss-field_cache_lifetime'
  $field_instances['bean-imagex_widget_rss-field_cache_lifetime'] = array(
    'bundle' => 'imagex_widget_rss',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'How often should the feed be updated? Enter a value in minutes that determines how often the feed will refresh.',
    'display' => array(
      'bucket_bar' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 2,
      ),
      'landing_page' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'mega_menu' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_cache_lifetime',
    'label' => 'Cache Lifetime',
    'required' => 0,
    'settings' => array(
      'max' => 99999,
      'min' => 0,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 33,
    ),
    'workbench_access_field' => 0,
  );

  // Exported field_instance: 'bean-imagex_widget_rss-field_widget_feed_link'
  $field_instances['bean-imagex_widget_rss-field_widget_feed_link'] = array(
    'bundle' => 'imagex_widget_rss',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'bucket_bar' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'default' => array(
        'label' => 'above',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 0,
      ),
      'landing_page' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'mega_menu' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_widget_feed_link',
    'label' => 'Feed Link',
    'required' => 1,
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'configurable_title' => 0,
        'rel' => '',
        'target' => 'default',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'rel_remove' => 'default',
      'title' => 'none',
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 31,
    ),
    'workbench_access_field' => 0,
  );

  // Exported field_instance: 'bean-imagex_widget_rss-field_widget_item_count'
  $field_instances['bean-imagex_widget_rss-field_widget_item_count'] = array(
    'bundle' => 'imagex_widget_rss',
    'default_value' => array(
      0 => array(
        'value' => 4,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'bucket_bar' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 1,
      ),
      'landing_page' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'mega_menu' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_widget_item_count',
    'label' => 'Items to Show',
    'required' => 1,
    'settings' => array(
      'max' => 25,
      'min' => 1,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 32,
    ),
    'workbench_access_field' => 0,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Cache Lifetime');
  t('Feed Link');
  t('How often should the feed be updated? Enter a value in minutes that determines how often the feed will refresh.');
  t('Items to Show');

  return $field_instances;
}
